workspace:
  base: /go
  path: src/github.com/karantin2020/beehive-docker

pipeline:
  publish:
    group: dopub
    image: plugins/docker
    repo: node3030/beehive
    secrets: [ docker_username, docker_password ]
    tag: [ 'latest', '0.2' ]
    when:
      branch: master
      event: push
      
  release:
    group: dopub
    image: plugins/docker
    repo: node3030/beehive
    secrets: [ docker_username, docker_password ]
    tags: ${DRONE_TAG##v}
    when:
      event: tag
